Fix tests

diff --git a/tests/multiver b/tests/multiver
--- a/tests/multiver
+++ b/tests/multiver
@@ -5,9 +5,9 @@ SCRIPT_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
 . "${SCRIPT_DIR}/../poshlib.sh" || exit 1
 use swine
 
-for v in 3.1 3.2 4.0 4.1 4.2 4.3 4.4 5.0; do
+for v in 3.2 4.0 4.1 4.2 4.3 4.4 5.0; do
     echo "Running tests on bash v$v"
     echo
-    docker run -v "$SCRIPT_DIR/..:/mnt" "bash:$v" bash -c "ln -s /usr/local/bin/bash /bin ; /mnt/tests/${1:-all}" || echo "FAILED on bash v$v"
+    docker run --rm -v "$SCRIPT_DIR/..:/mnt" "bash:$v" bash -c 'ln -s /usr/local/bin/bash /bin ; for i in '"${*:-all}"'; do /mnt/tests/$i; done' || echo "FAILED on bash v$v"
     echo
 done
