implement try/catch

diff --git a/tests/test-010-swine b/tests/test-010-swine
--- a/tests/test-010-swine
+++ b/tests/test-010-swine
@@ -36,5 +36,35 @@ if [ "$output" != "errexit 2 on line 4 $tempfile" ]; then
 fi
 rm $tempfile
 
+# try/catch
+
+fail() {
+    return 1
+}
+
+fail-hard() {(
+    exit 2
+)}
+
+try fail
+if ! catch foo || [ $foo != 1 ]; then
+     die 1 "1 Failure in catch $foo"
+fi
+
+try fail-hard
+if ! catch foo || [ $foo != 2 ]; then
+    die 1 "2 Failure in catch $foo"
+fi
+
+try false
+if ! catch foo || [ $foo != 1 ]; then
+     die 1 "3 Failure in catch $foo"
+fi
+
+try true
+if catch foo; then
+    die 1 "4 Failure in catch $foo"
+fi
+
 # die
 die 0 "" 2>/dev/null
