Fix job-pool and rposh to work on mac, docker

diff --git a/tests/test-050-job-pool b/tests/test-050-job-pool
--- a/tests/test-050-job-pool
+++ b/tests/test-050-job-pool
@@ -2,25 +2,30 @@
 # shellcheck disable=SC1090,SC1091
 . "$(dirname "${BASH_SOURCE[0]}")/../poshlib.sh" || exit 1
 use swine
+use wc
 use job-pool
 
+tempfile=$(mktemp)
+
+write-test() {
+    echo "$*" >> "$tempfile"
+}
+
 # initialise threadpool
-job-pool.init 4 debug
+job-pool.init 4 0
 
-lines=$({
-    for i in 0 1 2 3 4 5 6 7 8 9; do
-        job-pool.run echo "$i"
-    done
+for i in 0 1 2 3 4 5 6 7 8 9; do
+    write-test "$i"
+done
 
-    # wait and clean up
-    e=
-    try job-pool.shutdown
-    if catch e; then
-        warn "Error $e shutting down threadpool"
-    fi
-} | wc -l)
+# wait and clean up
+e=
+try job-pool.shutdown
+if catch e; then
+    warn "Error $e shutting down threadpool"
+fi
 
-[[ $lines == 10 ]] || die 254 "Wrong number of lines printed"
+[[ $(wc.lines < "$tempfile") == 10 ]] || die 254 "Wrong number of lines printed"
 
 # shellcheck disable=SC2154
 exit "$job_pool_nerrors"
diff --git a/tests/test-210-rposh b/tests/test-210-rposh
--- a/tests/test-210-rposh
+++ b/tests/test-210-rposh
@@ -5,6 +5,7 @@ use swine
 use rposh
 
 if [ "${1:-}" == "" ]; then
+    ssh localhost true || die 0 "rposh cannot be tested without ssh, skipping test..."
     result=$(
         e=
         try rscript ",localhost,," --ssh-user="$USER" --sudo-user="$USER" "${BASH_SOURCE[0]}" '\[last\]' 'SHOULD NOT BE DISPLAYED'
